### PR TITLE
Prevent BitcoinLike UTXO picker from using tx<Dust

### PR DESCRIPTION
**Pull request by gagbo**
Prevent picker from using UTXO when the amount is less than dustAmount

Small issue with local tests, so using CI for now.

### CODE REVIEW

**Comment by gagbo** [comment]
HODL, I finally built my tests and it fails :(

**Comment by gagbo** [comment]
It's fine now. I had to make a few changes to BitcoinMakeBaseTransaction test class to make it work though.

**Comment by phaazon** [comment]
Hello,

Can we merge this? :) ping @gagbo @alekece

**Comment by gagbo** [comment]
> Hello,
> 
> Can we merge this? :) ping @gagbo @alekece

HODL status was because I didn't have a good test, I fixed it since so I'm confident about merging this (porting to design/modularization might take a little time depending on how test fixtures need to be migrated)

**Comment by phaazon** [comment]
I think we need to merge this. @YBadiss has already found a case that would have used this! :)

**Pull request merged**
