### PR TITLE
Changed the ownership mechanism of LevelDB in PreferencesBackend.

### PR DESCRIPTION
**Pull request by phaazon**
Instead of having a non-owning unordered_map and lots of owning
`shared_ptr` everywhere in the codebase, we now have an owning table and
weak_ptr everywhere. The idea is that, if we get a
`shared_ptr<ledger::core::PreferencesBackend>`, the underlying database is
handled via a weak_ptr. Which means that you have to lock it in order to
use the database, which allows us to destroy the database and observe it
everywhere.

Fixes LLC-198

### CODE REVIEW

**Comment by phaazon** [comment]
I’m actually going to make a very small reproducible example to show the problem.

**Comment by phaazon** [comment]
The following demonstrates the problem of our current code.

```cpp
// g++ -std=c++1y weak.cpp

#include <iostream>
#include <memory>
#include <string>
#include <unordered_map>

using namespace std;

// The scarce resource. No two instances can live at the same time in memory (i.e. lockfile).
struct Scarce {
  Scarce() {
    cout << "Scarce created" << endl;
  }

  ~Scarce() {
    cout << "Scarce dropped" << endl;
  }
};

// Preferences just holds a pointer to the scarce resource
struct Preferences {
  ~Preferences() {
    cout << "Preferences dropped" << endl;
  }

  // Simulate what happens when a thread dies.
  static void clear() {
    CACHE.clear();
  }

  // Get an instance of a scarce resource. If it’s already in memory, we don’t have to create it
  // but can use the cached version
  static shared_ptr<Scarce> obtain_instance(string const& name) {
    auto it = CACHE.find(name);

    if (it != CACHE.end()) {
      // cached resource, we just return it if it’s viable
      auto scarce = it->second.lock();
      if (scarce != nullptr) {
        return scarce;
      }
    }

    // the resource is not cached; create it
    auto scarce = make_shared<Scarce>();
    CACHE[name] = scarce;

    return scarce;
  }

private:
  shared_ptr<Scarce> _scarce;
  static unordered_map<string, weak_ptr<Scarce>> CACHE;
};

unordered_map<string, weak_ptr<Scarce>> Preferences::CACHE;

int main() {
  cout << "starting" << endl;

  {
    // get the first instance
    auto x = Preferences::obtain_instance("foo");
    auto y = Preferences::obtain_instance("foo"); // shouldn’t create
    auto z = Preferences::obtain_instance("foo"); // shouldn’t create
  }

  // here, the inst shared_ptr is not accessible and has been dropped; everything’s fine

  // now consider the following: a thread ask for an instance and keeps it around, but we reset
  // the Preferences
  {
    auto x = Preferences::obtain_instance("foo");
    Preferences::clear();
    auto y = Preferences::obtain_instance("foo"); // create while x is still living!
  }

  cout << "ending" << endl;
}
```

**Comment by phaazon** [comment]
And this demonstrates the correct path:

```cpp
// g++ -std=c++1y weak.cpp

#include <iostream>
#include <memory>
#include <string>
#include <unordered_map>

using namespace std;

// The scarce resource. No two instances can live at the same time in memory (i.e. lockfile).
struct Scarce {
  Scarce() {
    cout << "Scarce created" << endl;
  }

  ~Scarce() {
    cout << "Scarce dropped" << endl;
  }
};

// Preferences just holds a pointer to the scarce resource
struct Preferences {
  ~Preferences() {
    cout << "Preferences dropped" << endl;
  }

  // Simulate what happens when a thread dies.
  static void clear() {
    CACHE.clear();
  }

  // Get an instance of a scarce resource. If it’s already in memory, we don’t have to create it
  // but can use the cached version
  static weak_ptr<Scarce> obtain_instance(string const& name) {
    auto it = CACHE.find(name);

    if (it != CACHE.end()) {
      // cached resource, we just return it if it’s viable
      auto scarce = it->second;
      if (scarce != nullptr) {
        return scarce;
      }
    }

    // the resource is not cached; create it
    auto scarce = make_shared<Scarce>();
    CACHE[name] = scarce;

    return scarce;
  }

private:
  shared_ptr<Scarce> _scarce;
  static unordered_map<string, shared_ptr<Scarce>> CACHE;
};

unordered_map<string, shared_ptr<Scarce>> Preferences::CACHE;

int main() {
  cout << "starting" << endl;

  {
    // get the first instance
    auto x = Preferences::obtain_instance("foo");
    auto y = Preferences::obtain_instance("foo"); // shouldn’t create
    auto z = Preferences::obtain_instance("foo"); // shouldn’t create
  }


  // here, the inst shared_ptr is not accessible and has been dropped; everything’s fine

  // now consider the following: a thread ask for an instance and keeps it around, but we reset
  // the Preferences
  {
    auto x = Preferences::obtain_instance("foo");
    cout << "resources will get dropped here" << endl;
    Preferences::clear();
    auto y = Preferences::obtain_instance("foo"); // create while x is still living!
  }

  cout << "ending" << endl;
}
```

**Comment by phaazon** [comment]
Ping @pollastri-pierre

**Comment by gre** [comment]
awesome. i hope this can be shipped soon.

**Comment by phaazon** [comment]
@gre I set @KhalilBellakrid as approver too but we already have three approvals and it’s a one-commit PR. If we can have QA testing that specific situation, I think we’re safe merging it.

**Pull request merged**
