### PR TITLE
Add LBRY Credits support

### PR DESCRIPTION
**Pull request by Nageki**

### CODE REVIEW

**Comment by tzarebczan** [comment]
Hey Ledger Team - my name is Tom and I'm from the LBRY team. Please let me know if you have any questions about this and how we can support an expedited process to get this integrated!

**Comment by gre** [comment]
for now we are not accepting PR adding coins, in a near future we should document the way to add new coins to our ecosystem. We'll update our Readme with the process when ready.

**Comment by kodxana** [comment]
Can you PR this?

**Comment by dalijolijo** [comment]
> for now we are not accepting PR adding coins, in a near future we should document the way to add new coins to our ecosystem. We'll update our Readme with the process when ready.

@gre Is the document to add new coins available? Where can I find the Readme for this process?

**Comment by phaazon** [comment]
Hello,

Yes, we now have a document about contribution and coin integration [here](https://github.com/LedgerHQ/lib-ledger-core/blob/master/CONTRIBUTING.md#about-coin-integration). Currently, we do not accept PRs about coin integration as it implies several internal discussions.

Nevertheless, I added this PR to wishlist #164. I’m sorry that I have to close this. Feel free to go on #164 for further details.

**Pull request closed without merging**
