### PR TITLE
Add an API to get memo attached to stellar transactions

### PR DESCRIPTION
**Pull request by pollastri-pierre**
This PR add a new feature and API to get a memo attached to a stellar transaction.

A memo is a tag added to a transaction, on stellar memo can have 5 different values (NONE, TEXT, ID, HASH, RETURN).

https://www.stellar.org/developers/guides/concepts/transactions.html#memo

### CODE REVIEW

**Comment by gre** [comment]
@pollastri-pierre does this mean we will need a regen on the bindings as well?

**Comment by pollastri-pierre** [comment]
> @pollastri-pierre does this mean we will need a regen on the bindings as well?

Yes we'll need to regen bindings for the new API.

**Comment by pollastri-pierre** [comment]
HODL we need an update on BigInt class to be able to merge this PR.

**Comment by phaazon** [comment]
@pollastri-pierre is this still `HODL`?

**Comment by pollastri-pierre** [comment]
> @pollastri-pierre is this still `HODL`?

I'm rebasing on develop and then we can merge.

**Pull request merged**
