### PR TITLE
Remove boost package installation

### PR DESCRIPTION
**Pull request by teams2ua**

### CODE REVIEW

**Comment by phaazon** [comment]
IIRC @pollastri-pierre might still need boost.

**Comment by teams2ua** [comment]
> IIRC @pollastri-pierre might still need boost.

We have header-only boost in test/libs/boost.
I remove package-installed boost  to avoid ambiguity, once we will have a need of builded libs from boost, but we will need to work out some common approach.

**Comment by KhalilBellakrid** [comment]
First, why are we doing this ? 
Second , if we really need this it's not ideal to have a `lib` depending on `test/lib` ...

**Comment by teams2ua** [comment]
> First, why are we doing this ?
> Second , if we really need this it's not ideal to have a `lib` depending on `test/lib` ...

I remove this in order to not have ambiguity (+ we don't need this), some libraries may do find_boost() in CMakeLists.txt so they will use the boost installed as a package, but other code will use directly included headers.
Yes, I think should move this to lib, can be done in separate review.

**Comment by pollastri-pierre** [comment]
👍 I'll do a PR if I need to add boost to our dependencies

**Pull request merged**
