### PR TITLE
XRP segregation

### PR DESCRIPTION
**Pull request by phaazon**

### CODE REVIEW

**Comment by phaazon** [comment]
_Oui, c’est le bordel oui._

**Comment by teams2ua** [comment]
Is it possible to split this commit in two - first one moving boost to lib/ and second actual changes?

**Comment by phaazon** [comment]
Sure, I will anyway rebase everything when times come up. :D

**Comment by phaazon** [comment]
I’m closing because it’s still not ready. I will re-open later.

**Pull request closed without merging**
