### PR TITLE
Normalize file names and header paths

### PR DESCRIPTION
**Pull request by alekece**
**DON'T BE A-FRAID !** 

I have been introduced a lot of changes but it's basically files renaming.

To make the naming in the code base consistent, I changed all file names that don't fit with **PascalCase** convention and replaced random ".h" extensions by ".hpp"
Moreover I allocated some times to remove all old header guards by `#pragma once` directive - this is supported by almost all compilers.
I also changed all relative header paths to the absolute ones as I precognized in the [draft](https://github.com/LedgerHQ/lib-ledger-core/blob/misc/coding-conventions/CONVENTIONS.md) convention.

### CODE REVIEW

**Comment by teams2ua** [comment]
AFAIR, we use `*.hpp` for files that contains template function or classes as there are some implementation inside, for all other cases we use `*.h`.
[FAR] It would be nice to redo djinni as well to have `#pragma once` in generated code

**Comment by phaazon** [comment]
For Djinni, I can take care of it.

**Comment by phaazon** [comment]
By default, `djinni` outputs as `.h`.

**Comment by alekece** [comment]
All capitalize renaming seems to be ignored... I'll fix that

**Comment by phaazon** [comment]
Wait wait I have a fix incoming.

**Pull request merged**
