### PR TITLE
Add NIX

### PR DESCRIPTION
**Pull request by mattt21**

### CODE REVIEW

**Comment by mattt21** [comment]
@phaazon Any updates on getting this merged?

**Comment by phaazon** [comment]
Hello @mattt21. We discussed coin integration internally and I have the regret to inform you that we _currently_ don’t accept PRs that add new coins (feel free to read [this](https://github.com/LedgerHQ/lib-ledger-core/blob/develop/CONTRIBUTING.md#about-coin-integration) for further information). As I know you might feel a bit frustrated about that, I apologize. Feel free to open an issue so that we can discuss NIX (btw that coin rocks!).

At another level, coin integration is something we want to be available and easy to do and, at some time, that kind of contribution should be possible. But please open an issue, having the need around is definitely something we want (I can’t say whether it’s likely or not NIX will be added soon or in a far future).

Thank you for your time.

**Comment by mattt21** [comment]
@phaazon Thanks for getting back to me :) NIX is already listed on ledger devices, I am not sure what you mean by "we _currently_ don’t accept PRs that add new coins" as NIX is not a new coin - unless you mean specifically to this repo.

**Comment by phaazon** [comment]
@mattt21 adding new “coins” (coin families, tokens, etc.).

I have to close this but I added it to #164, so feel free to comment if you need more information. Thank you for contribution and again, sorry for the delay and the frustration you might have felt towards that topic.

Thank you.

**Pull request closed without merging**
