### PR TITLE
fix(btc): correct prev output in optimistic update

### PR DESCRIPTION
**Pull request by gagbo**
As we merge foreign outputs in BTC-like currencies, we cannot directly
access the "previous transaction" output with the index. It is necessary
to scan every output and find it with a matching predicate

Fixes VSD-678

### CODE REVIEW

**Review by pollastri-pierre — APPROVED** [review]

**Review by twilgenbus-ledger — APPROVED** [review]
LGTM

Only thing is maybe we could make it easier to read that critical code by abstracting the whole "findPrevTxOutputValue" in its own tiny function. Wdyt?

**Comment by gagbo** [comment]
> LGTM
> 
> Only thing is maybe we could make it easier to read that critical code by abstracting the whole "findPrevTxOutputValue" in its own tiny function. Wdyt?

yeah why not, it's going to be a bigger PR though

**Review by twilgenbus-ledger — APPROVED** [review]
That's a lot better than what I had proposed, but it feels a lot better now! Ready to merge imo.

**Comment by gagbo** [comment]
Merging even if CI is red as only Cosmos related tests fail (probably because of Stargate-related changes) and this version of Core is targeted for Vault

**Pull request merged**
